name: Crowdin Download

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  download-from-crowdin:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: false
          download_translations: true
          import_eq_suggestions: true
          skip_untranslated_strings: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          commit_message: "chore(i18n): translation updates [skip ci]"
          pull_request_title: 'chore(i18n): New Crowdin Translations [skip ci]'
          pull_request_body: 'New crowdin translations imported from the GitHub action.'
          pull_request_base_branch_name: 'main'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}