name: "Release"

on:
  push:
    tags:
      - "v*.*.*.*"

permissions:
  contents: write

jobs:
  Plugin:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Get Tag Name
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Setup Dalamud
        uses: Blooym/setup-dalamud@v1
        with:
          branch: release

      - name: Restore Project
        working-directory: Wholist
        run: dotnet restore

      - name: Build Project
        shell: bash
        working-directory: Wholist
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ env.tag }}
          sha512sum bin/x64/Release/Wholist/latest.zip  >> checksums.txt
          cat checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          append_body: true
          body_path: .github/release_notices.md
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            Wholist/bin/x64/Release/Wholist/latest.zip
            Wholist/checksums.txt